services:
  apache:
    build: ./apache
    container_name: apache_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/certs:/etc/apache2/ssl
      - ./logs/apache:/var/log/apache2
      - ./www/html/local:/var/www/html/local
      - ./www/html/om2012:/var/www/html/om2012
      - ./www/html/sbg-desktop:/var/www/html/sbg-desktop
      - ./www/html/cms:/var/www/html/cms
      - ./www/html/sbg-laravel:/var/www/html/sbg-laravel
    depends_on:
      - php71
      - php74
      - php82
    networks:
      custom_network:
        ipv4_address: 192.168.100.4  # Static IP for Apache
    extra_hosts:
      - host.docker.internal:host-gateway    

  php71:
    build: ./php/php71
    container_name: php71_fpm
    volumes:
      - ./logs/php/php71:/var/log/php
      - ./php/php71/php.ini:/usr/local/etc/php/php.ini
      - ./www/html/local:/var/www/html/local
    networks:
      custom_network:
        ipv4_address: 192.168.100.5  # Static IP for PHP 7.1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php74:
    build: ./php/php74
    container_name: php74_fpm
    volumes:
      - ./logs/php/php74:/var/log/php
      - ./php/php74/php.ini:/usr/local/etc/php/php.ini
      - ./www/html/sbg-desktop:/var/www/html/sbg-desktop
      - ./www/html/om2012:/var/www/html/om2012
      - ./www/html/local:/var/www/html/local
    networks:
      custom_network:
        ipv4_address: 192.168.100.6  # Static IP for PHP 7.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php82:
    build: ./php/php82
    container_name: php82_fpm
    volumes:
      - ./logs/php/php82:/var/log/php
      - ./php/php82/php.ini:/usr/local/etc/php/php.ini
      - ./www/html/cms:/var/www/html/cms
      - ./www/html/sbg-laravel:/var/www/html/sbg-laravel
      - ./www/html/local:/var/www/html/local
    networks:
      custom_network:
        ipv4_address: 192.168.100.9  # Static IP for PHP 8.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

### remove custom_network: docker network rm custom_network
### create a custom_network manually: docker network create --driver bridge --subnet 192.168.100.0/24 custom_network
networks:
  custom_network:
    external: true
